name: release-please
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version-file: '.node-version'
          registry-url: https://registry.npmjs.org/
      - name: Update npm to latest version
        if: ${{ steps.release.outputs.release_created }}
        run: npm install -g npm@latest
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}

  docker-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker.yml
    with:
      release_tag: ${{ needs.release-please.outputs.tag_name }}
